<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AssemblyName>Restitutor_fixes_trade_exp</AssemblyName>
    <Version>0.1.1</Version>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="EntryPoint.cs" />
    <EmbeddedResource Include="evidence/*.bin" />
    <Reference Include="MelonLoader"><HintPath>E:\Program\steam\steamapps\common\Sailing Era\MelonLoader\net6\MelonLoader.dll</HintPath><Private>false</Private></Reference>
  </ItemGroup>
</Project>
